### ISSUE TITLE
Business Logic Classes

### ISSUE THREAD

**Issue by sarahpadlipsky** [cpe305/fall2016-project-sarahpadlipsky#1]
Follow the BussinessLogicClasses diagram found in the diagrams tab, to make the simple classes for User, Group, and SuperUser. All three of these classes (for now) rely mostly on getters and setters so these should be easy to implement.

You may push these directly to my working branch. However, if you feel more comfortable, you can make your own branch and I will integrate them later.

Please put these files in fall2016-project sarahpadlipsky/app/src/main/java/com/example/sarahpadlipsky/iou/ where the other classes such as Main.java and GroupActivity.java are currently.

**Comment by cesiu** [comment]
Made a pull request.

**Comment by sarahpadlipsky** [comment]
Fixed with 529d437. Thanks!
